language: node_js
node_js:
 - "node"
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_REPORTER_ID

  addons:
    code_climate:
      repo_token: $CODE_CLIMATE_TOKEN

before_script:
  - npm run migrate

install:
  - npm install

script: npm run migrate && npm test

after_success:
  -  npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT